"""Common domain models and schemas for AI Remote Desktop."""

from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field


class ActionType(str, Enum):
    MOUSE_MOVE = "mouse_move"
    MOUSE_CLICK = "mouse_click"
    MOUSE_DOUBLE_CLICK = "mouse_double_click"
    MOUSE_RIGHT_CLICK = "mouse_right_click"
    MOUSE_DRAG = "mouse_drag"
    MOUSE_SCROLL = "mouse_scroll"
    TYPE_TEXT = "type_text"
    KEY_PRESS = "key_press"
    HOTKEY = "hotkey"
    WAIT = "wait"
    EXECUTE_COMMAND = "execute_shell_command"
    TERMINATE = "terminate"


class RiskTier(str, Enum):
    TIER_1_SAFE = "tier_1_safe"
    TIER_2_MODERATE = "tier_2_moderate"
    TIER_3_HIGH_RISK = "tier_3_high_risk"


class AIAction(BaseModel):
    """Structured action generated by Multimodal VLM."""
    thought: str = Field(..., description="Internal step reasoning of the model")
    action_type: ActionType
    parameters: Dict[str, Any] = Field(default_factory=dict)
    expected_outcome: Optional[str] = None
    is_terminal: bool = False
    risk_tier: RiskTier = RiskTier.TIER_1_SAFE


class ScreenPoint(BaseModel):
    """Normalized screen coordinates [0.0, 1.0]."""
    x: float = Field(..., ge=0.0, le=1.0)
    y: float = Field(..., ge=0.0, le=1.0)


class SessionPermissions(BaseModel):
    """Granular permissions granted to the remote session or AI Copilot."""
    allow_mouse_keyboard: bool = True
    allow_clipboard_sync: bool = True
    allow_audio_listen: bool = True
    allow_file_transfer: bool = True
    allow_ai_autonomous: bool = True
    require_hitl_approval: bool = True
    allow_system_reboot: bool = False


class TaskStepResult(BaseModel):
    """Result of an executed AI task step."""
    step_number: int
    action: AIAction
    success: bool
    message: str
    execution_time_ms: float
    screenshot_before_b64: Optional[str] = None
    screenshot_after_b64: Optional[str] = None
